### ISSUE TITLE
"hgroup" and "menu" test cases and HTML 5.2

### ISSUE THREAD

**Issue by peteroupc** [html5lib/html5lib-tests#120]
In `blocks`, the following test cases no longer correspond to HTML 5.2, since `hgroup` is now an ordinary element, and not a "special" element.

    <!doctype html><p>foo<hgroup>bar<p>baz

In that test case, an implied `</p>` end tag is no longer generated before the `<hgroup>` start tag.

    <!doctype html><hgroup><p>foo</hgroup>bar

In that test case, the `</hgroup>` end tag is now ignored since the current node at that end tag is `<p>`, which is special.

In addition, two test cases involving `<menu>` no longer correspond to HTML 5.2, for the same reason as with `<hgroup>`:

    <!doctype html><p>foo<menu>bar<p>baz
    <!doctype html><menu><p>foo</menu>bar

**Comment by peteroupc** [comment]
This also affects the following `<menu>` test case (in `template`):

    <body><template><i><menu>Foo</i>

**Comment by annevk** [comment]
This should be closed as HTML 5.2 is obsolete.
