### ISSUE TITLE
The <search> element is not in the spec

### ISSUE THREAD

**Issue by ju1ius** [html5lib/html5lib-tests#156]
Hi,

#142 added tests for the `<search>` element, but it is not in the HTML spec yet (no documentation about it can be found when building the main branch of the spec).

Looking at the state of whatwg/html#7320, it looks like it's still a long way before it lands.

It seems to me that this PR should not have been merged before whatwg/html#7320 was either merged or reached a more stable state.

If you disagree, could you consider adding a way to filter-out test-cases for experimental parts of the spec?
For example by putting them in an `experimental` subdirectory (like it's done for [scripting-related tests](tree-construction/scripted))?

Thanks !

**Comment by annevk** [comment]
Hey @ju1ius, thanks for the reminder. @gsnedders wrote https://github.com/web-platform-tests/wpt/pull/39158 which was the main blocker towards getting the `<search>` element over the finish line, so you might have inadvertently helped make it happen. Stay tuned.
